### PR TITLE
Delete user

### PR DESCRIPTION
**Pull request by ChexWarrior**
@kd90693n This works, however we should probably add a dialog warning the user, right now it just deletes their account as soon as they press the button.

Associated Issue: #8

### CODE REVIEW

**Comment by ChexWarrior** [comment]
Oh, we should also display a message saying the user has been deleted.

**Comment by ChexWarrior** [comment]
Also, as a note to myself the code responsible for the actual deletion needs to be refactored into a method somewhere, it will get used again.

**Comment by ChexWarrior** [comment]
@kd90693n @perryc85 I wanted to mention that this issue is a great example of cascading deletes.  Since Users create Businesses and each of the Businesses has Activities, what should happen when a user is deleted? My implementation deletes each Business created by the deleted User and also deletes each Activity tied to each of those Businesses.  

Something to think about,it's a very common situation in software applications.

**Comment by kd90693n** [comment]
@ChexWarrior I think that actually works for our application. If a user is deleted we don't want to their business or activities that may be outdated or no longer valid.

We may want to consider before deleting advising the user that they have a business and active activities that will be erased with it if they don't switch it to another user. This is not in the plan for this semester so we can just go with the top part in deleting all.

**Comment by ChexWarrior** [comment]
Adding a message is actually more difficult than it seems, I can explain this in person, I'll merge this for now.

**Pull request merged**
