### PR TITLE
created business page and added header

### PR DESCRIPTION
**Pull request by perryc85**

### CODE REVIEW

**Comment by ChexWarrior** [comment]
@perryc85 Is this WIP or ready to go?

**Comment by perryc85** [comment]
@ChexWarrior - It is good to go. Kevin is building the form with today's attendees. I won't be there because I have class tonight.

**Comment by perryc85** [comment]
@ChexWarrior - Wait, I need to run that command. I forgot.

**Comment by ChexWarrior** [comment]
Which command?

**Comment by perryc85** [comment]
This one -- `npx node-sass public/assets/sass/styles.scss public/assets/css/styles.css`

**Comment by ChexWarrior** [comment]
That will only change styles for you, we aren't committing the `style.css` file anymore.

**Comment by ChexWarrior** [comment]
Also can you tell me what this page is for? Is it for a single business or all businesses?

**Comment by perryc85** [comment]
I believe all

**Comment by ChexWarrior** [comment]
Still not sure what you mean? Was this page tied to a particular user? In that case it would show all businesses that user created. We can discuss later, I'll also bring it up with the group tonight.

cc @kd90693n

**Comment by kd90693n** [comment]
This relates to the 1.5 Modify profile information module
  - ability for a business user to enter and edit their business info

I was thinking for simplicity, one user - one business(we can improve on it and make it one to many business but I think to continue to have everyone understand fixtures, forms, and routes keeping it to one for now is good. Focusing the next iterations on the actual activities.). This page should contain a form just like the profile page that includes the business fields.

- business name
- tax id
- address 1
- address 2
- zip
- city
- state
- country
- description

This pull request specifically is only the creation of the page where more will go in.

**Comment by ChexWarrior** [comment]
Going to make some changes

**Pull request merged**
